#' Example Seurat Object for Testing
#'
#' A simulated Seurat object with fake gene expression data for the Wnt signaling pathway.
#' This Seurat object contains gene expression data from simulated cells with Wnt positive
#' and negative gene expression values.
#'
#' @format A Seurat object. The object contains:
#' \describe{
#'   \item{assays}{List of assays used for data storage. Includes RNA expression data.}
#'   \item{meta.data}{Metadata associated with the cells. Contains information about the groups (e.g., WT vs. Mutant).}
#'   \item{features}{Gene features (including Wnt pathway genes) used in the analysis.}
#'   \item{cells}{Cell names, labeled as Cell1, Cell2, ..., CellN.}
#' }
#' @source Simulated for demonstration purposes.
#' @usage data(fake_test_object)
"fake_test_object"


#' Example Cell Status and Normalized Data
#'
#' A dataset generated by `ComputeCellData` applied to `fake_test_object`.
#' Contains cell status and normalized values.
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{V1}{A numerical value presenting the status of the cell}
#'   \item{normalized}{Numerical value representing normalized data}
#' }
#' @usage data(fake_final_mds)
#' @examples
#' data(fake_final_mds)
#' head(fake_final_mds)
#' @keywords datasets
"fake_final_mds"

#' Example Processed Data for Plotting
#'
#' A dataset generated by running `PreparePlotData` on `fake_test_object` and `fake_final_mds`.
#' Contains processed data ready for visualization, with the following features:
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{V1}{A numerical or categorical value depending on the specific analysis}
#'   \item{normalized}{Normalized numerical value representing the cell's data}
#'   \item{genotype}{Group classification of the cell (e.g., "WT", "Mutant")}
#'   \item{scale}{Scaled data for visualization purposes}
#' }
#' @usage data(fake_to_plot)
#' @examples
#' data(fake_to_plot)
#' head(fake_to_plot)
#' @keywords datasets
"fake_to_plot"


