#' Example Seurat Object for Testing
#'
#' A simulated Seurat object with fake gene expression data for the Wnt signaling pathway.
#' This Seurat object contains gene expression data from simulated cells with Wnt positive
#' and negative gene expression values.
#'
#' @format A Seurat object. The object contains:
#' \describe{
#'   \item{assays}{List of assays used for data storage. Includes RNA expression data.}
#'   \item{meta.data}{Metadata associated with the cells. Contains information about the groups (e.g., WT vs. Mutant).}
#'   \item{features}{Gene features (including Wnt pathway genes) used in the analysis.}
#'   \item{cells}{Cell names, labeled as Cell1, Cell2, ..., CellN.}
#' }
#' @source Simulated for demonstration purposes.
#' @usage data(fake_test_object)
"fake_test_object"

#' Example Matrix for Testing
#'
#' A numeric matrix containing single-cell gene expression data for demonstration purposes in the PathwayEmbed package.
#' Rows correspond to genes and columns correspond to individual cells.
#'
#' @format A numeric matrix with genes (rows) and cells (columns).
#' \describe{
#'   \item{Rows}{18 genes (e.g. "Lgr5", "Rnf43", "Lrp5", "Fzd6" ...)}
#'   \item{Columns}{2000 cells (named "Cell1", "Cell2", ...)}
#'   \item{Values}{35830 nonzero entries, representing expression values (numeric)}
#' }
#' @source Simulated for demonstration purposes.
#' @details
#' This is a synthetic dataset created for testing and demonstration purposes.
#' It mimics the structure of a gene-by-cell expression matrix used in single-cell
#' RNA sequencing analysis.
#'
#' @examples
#' data(fake_test_matrix)
"fake_test_matrix"

#' Fake metadata for test cells
#'
#' A toy metadata table corresponding to the columns of `fake_test_matrix`.
#' Each row represents a single cell with associated metadata.
#'
#' @format A data frame with 2000 rows and 4 variables:
#' \describe{
#'   \item{orig.ident}{Character, project identifier}
#'   \item{nCount_RNA}{Integer, total RNA counts per cell}
#'   \item{nFeature_RNA}{Integer, number of detected features (genes) per cell}
#'   \item{genotype}{Factor/character, cell genotype (e.g., "WT", "Mutant")}
#' }
#'
#' @details
#' This dataset provides toy cell-level metadata designed to accompany
#' `fake_test_matrix`. It mimics the structure of single-cell
#' experiment metadata used in analysis frameworks such as Seurat.
#'
#' @examples
#' data(fake_test_metadata)
"fake_test_metadata"


#' Example Cell Status and Normalized Data
#'
#' A dataset generated by `ComputeCellData` applied to `fake_test_matrix`.
#' Contains cell status and normalized values.
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{V1}{A numerical value presenting the status of the cell}
#'   \item{normalized}{Numerical value representing normalized data}
#' }
#' @usage data(fake_final_mds)
#' @examples
#' data(fake_final_mds)
#' head(fake_final_mds)
#' @keywords datasets
"fake_final_mds"


#' Example Processed Data for Plotting
#'
#' A dataset generated by running `PreparePlotData` on `fake_test_metadata` and `fake_final_mds`.
#' Contains processed data ready for visualization, with the following features:
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{V1}{A numerical or categorical value depending on the specific analysis}
#'   \item{normalized}{Normalized numerical value representing the cell's data}
#'   \item{genotype}{Group classification of the cell (e.g., "WT", "Mutant")}
#'   \item{scale}{Scaled data for visualization purposes}
#' }
#' @usage data(fake_to_plot)
#' @examples
#' data(fake_to_plot)
#' head(fake_to_plot)
#' @keywords datasets
"fake_to_plot"


